version: '3'
services:
    spot-termination-poller:
        build: .
#        command: ["60"]
        container_name: spot-termination-poller
        network_mode: "host"
        stdin_open: true
        tty: true
