version: '3'
services:
    spot-termination-poller:
        build: .
#        command: ["60"]
        container_name: spot-termination-poller
        network_mode: "host"
        stdin_open: true
        tty: true
        environment:
            POLL_INTERVAL: 5
            NOTICE_URL: http://169.254.169.254/latest/meta-data/spot/termination-time
